
services:
  - type: web
    name: discord-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_BACKUP_REPO
        sync: false
