services:
- type: web
  name: discord-bot
  env: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: python paste.txt
  envVars:
    - key: DISCORD_BOT_TOKEN
      sync: false
    - key: GITHUB_TOKEN
      sync: false
    - key: GITHUB_BACKUP_REPO
      sync: false